"""Markdown certificate + artifact writer under runs/."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from causalaudit.checklist import AuditResult


def render_certificate_md(result: AuditResult) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Causal Compliance Certificate",
        "",
        f"**Claim:** {result.title}",
        f"**Verdict:** {'PASS' if result.passed else 'FAIL'}",
        f"**Score:** {result.score:.1%}",
        f"**Issued:** {ts}",
        "",
        result.summary,
        "",
        "## Checklist",
        "",
        "| ID | Required | Result | Description | Detail |",
        "|----|----------|--------|-------------|--------|",
    ]
    for c in result.checks:
        mark = "PASS" if c.passed else "FAIL"
        req = "yes" if c.required else "no"
        detail = c.detail.replace("|", "/")[:80]
        lines.append(
            f"| `{c.id}` | {req} | **{mark}** | {c.description} | {detail} |"
        )
    lines += [
        "",
        "## Claim snapshot",
        "",
        "```json",
        json.dumps(result.report, indent=2),
        "```",
        "",
        "---",
        "_Generated by causalaudit (Causal Compliance Auditor). Not legal advice._",
        "",
    ]
    return "\n".join(lines)


def write_certificate(
    result: AuditResult,
    runs_dir: str | Path = "runs",
    slug: str | None = None,
) -> Path:
    root = Path(runs_dir)
    root.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    safe = (slug or result.title).lower()
    safe = "".join(ch if ch.isalnum() or ch in "-_" else "-" for ch in safe)[:40]
    run_dir = root / f"{ts}_{safe}"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "audit.json").write_text(
        json.dumps(result.to_dict(), indent=2), encoding="utf-8"
    )
    md = render_certificate_md(result)
    cert = run_dir / "certificate.md"
    cert.write_text(md, encoding="utf-8")
    return run_dir
